# Generated by Django 2.2 on 2020-10-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201014_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient_recipe',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Количество'),
        ),
    ]
