# Generated by Django 2.2 on 2020-10-17 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20201014_1513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient_Recipe',
            new_name='IngredientRecipe',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='recipes.Recipe', verbose_name='Рецепты'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
